#!/bin/bash

PACKAGES='Custom-Event Mobile Class-Extras History Form-AutoGrow Form-Placeholder DynamicMatcher Element-Wait EventStack ScrollLoader Tree Interface'
PACKAGER=$1

if [ -z "$PACKAGER" ]; then
	PACKAGER=$(which packager || echo './packager')
fi

if [ ! -x "$PACKAGER" ]; then
	echo "Usage: $0 [packager]"
	echo
	echo 'arguments:'
	echo '  packager    Path to packager executable. If not given, it tries to find'
	echo '              packager in your $PATH, then in your current working directory.'
	exit 1
fi

COMPONENTS=$(echo $PACKAGES | sed "s/\([^ ]*\)/'\1\/*'/g")
bash -c "$PACKAGER build $COMPONENTS +use-only $PACKAGES"
